#!/usr/bin/python3

import sys

def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return i, n // i
    return None, None

if len(sys.argv) != 2:
    print("Usage: python factors.py <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            if p is not None:
                print("{}={}*{}".format(n, p, q))

except FileNotFoundError:
    print("File '{}' not found.".format(input_file))
except ValueError:
    print("Invalid input in the file. Please make sure all lines contain valid natural numbers greater than 1.")

