#!/usr/bin/python3

import sys

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

def factorize(n):
    for i in range(2, n + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return i, n // i
    return None, None

if len(sys.argv) != 2:
    print("Usage: python rsa.py <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            if p is not None:
                print("{}={}*{}".format(n, p, q))
            else:
                print("Unable to factorize the number {} into two prime factors.".format(n))

except FileNotFoundError:
    print("File '{}' not found.".format(input_file))
except ValueError:
    print("Invalid input in the file. Please make sure all lines contain valid RSA numbers.")

